[platformio]
default_envs = m5stack-core2

[env:m5stack-core2]
platform = espressif32@6.13.0
board = m5stack-core2
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  m5stack/M5Unified @ 0.2.10
  bblanchon/ArduinoJson @ 6.21.5
build_flags =
  -DCORE_DEBUG_LEVEL=1

[env:m5stack-tab5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = m5stack-tab5-p4
framework = arduino
extra_scripts = pre:scripts/patch_nimble_duplicate_characteristics.py
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  m5stack/M5Unified @ 0.2.10
  bblanchon/ArduinoJson @ 6.21.5
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DCODEX_BOARD_TAB5=1
